import { ConvexHttpClient } from "convex/browser";
import { api } from "../../../../convex/_generated/api";
import { SITE, absoluteUrl } from "@/lib/site";

const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL;

async function loadPreset(id) {
  if (!CONVEX_URL) return null;
  try {
    const client = new ConvexHttpClient(CONVEX_URL);
    return await client.query(api.presets.get, { id });
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }) {
  const { id } = await params;
  const preset = await loadPreset(id);

  if (!preset || !preset.isPublic) {
    return {
      title: "Preset",
      robots: { index: false, follow: true },
    };
  }

  const title = preset.name;
  const description =
    preset.description ||
    `A reusable ${preset.tool || "shell"} command recipe for ${preset.category || "files"} — generated by ReFile.`;
  const url = absoluteUrl(`/presets/${id}`);

  return {
    title,
    description,
    keywords: [
      preset.name,
      preset.tool,
      preset.category,
      ...(preset.tags ?? []),
      `${preset.tool} preset`,
      `${preset.category} preset`,
    ].filter(Boolean),
    alternates: { canonical: url },
    openGraph: {
      title: `${title} — ${SITE.name}`,
      description,
      url,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} — ${SITE.name}`,
      description,
    },
  };
}

export default function PresetIdLayout({ children, params }) {
  // Wrap with JSON-LD HowTo so search engines can surface this as a how-to result.
  return (
    <>
      <PresetJsonLd params={params} />
      {children}
    </>
  );
}

async function PresetJsonLd({ params }) {
  const { id } = await params;
  const preset = await loadPreset(id);
  if (!preset || !preset.isPublic) return null;

  const url = absoluteUrl(`/presets/${id}`);
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: preset.name,
    description: preset.description || "",
    url,
    tool: [{ "@type": "HowToTool", name: preset.tool }],
    step: {
      "@type": "HowToStep",
      name: "Run the command",
      text: preset.commandTemplate,
    },
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}
